routes/web.php
<?php

/* 		Frontend 	*/
//////////////////////
Route::get('/', function () { return view('welcome'); });


 /*		Backend 	*/
 /////////////////////
 
 /*dashboard*/
Route::get('/admin','BackendController@Index');

/* Aplikasi */
Route::resource('BackendController','BackendController');
Route::get('/admin/aplikasi','BackendController@Aplikasi');

Route::get('/admin/aplikasi/tambah','BackendController@Tambah_aplikasi');

/* Kategori */
Route::get('/admin/kategori','BackendController@Kategori');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

use Illuminate\Support\facades\DB;

use Illuminate\Http\Request;
use App\Http\Requests;

use App\model\Aplikasi;

class BackendController extends BaseController{
	use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

	public function Index(){
		return view('backend.dashboard');	
	}

	public function Aplikasi(Request $request){

		$this->validate($request, [
			'limit' => 'integer',
		]);

		$keyword 			= $request->get('keyword');
		$kategori_aplikasi  = $request->get('kategori_aplikasi');
		$tahun_lulus		= $request->get('tahun_lulus');
		
		$data = Aplikasi::where('nama_aplikasi', 'LIKE', '%' . $keyword . '%')
						  ->where('kategori_aplikasi', 'LIKE', '%' . $kategori_aplikasi. '%')
						  ->where('tahun_lulus', 'LIKE', '%' . $tahun_lulus. '%')
						  ->paginate($request->limit ? $request->limit : 5);

		$data->appends($request->only('keyword', 'kategori_aplikasi', 'tahun_lulus', 'limit'));

		return view('backend.aplikasi', compact('data', 'keyword', 'kategori_aplikasi', 'tahun_lulus'));
	}

	public function Tambah_aplikasi(){
		return view('backend.tambah_aplikasi');
	}

	public function store(Request $request){
		$data 						= new Aplikasi();
		$data->nama_aplikasi 		= $request->input('nama_aplikasi');
		$data->kategori_aplikasi 	= $request->input('kategori_aplikasi');;
		$data->nim 					= $request->input('nim');
		$data->nama_pembuat 		= $request->input('nama_pembuat');
		$data->tahun_lulus 			= $request->input('tahun_lulus');
		$data->deskripsi_aplikasi 	= $request->input('deskripsi_aplikasi');
		$data->alamat_tautan 		= $request->input('alamat_tautan');

		$file = $request->file('gambar_aplikasi');
		$ext = $file->getClientOriginalExtension();
		$newName = rand(100000,1001238912).".".$ext;
		$file->move('uploads/gambar_aplikasi',$newName);
		$data->gambar_aplikasi = $newName;

		$data->save();
		return redirect('/admin/aplikasi')->with('alert-success','Data berhasil ditambahkan!');
	}

	public function Kategori(){
		return view('backend.kategori');
	}

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/backend/aplikasi.blade.php
@extends('backend.layout.index')
@section('content')
<!-- Dashboard -->

<!-- Content -->
<div class="dashboard-content">

	<!-- Titlebar -->
	<div id="titlebar">
		<div class="row">
			<div class="col-md-12">
				<h2>Howdy, Tom!</h2>
				<!-- Breadcrumbs -->
				<nav id="breadcrumbs">
					<ul>
						<li><a href="#">Home</a></li>
						<li>Aplikasi</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>

	<!-- Notice -->
	@if(Session::has('alert-success'))
	<div class="row">
		<div class="col-md-12">
			<div class="notification success closeable margin-bottom-30">
				<div class="alert alert-success">
					<strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
				</div>
				<a class="close" href="#"></a>
			</div>
		</div>
	</div>
	@endif

	<!-- Content -->

	<div class="row">
		<form action="{{ url()->current() }}" method="GET" autocomplete="off">
			<div class="col-md-12">
				<div class="col-md-5">
					<input type="text" name="keyword" placeholder="Masukan Kata Kunci">
				</div>
				<div class="col-md-3">
					<select name="kategori_aplikasi">
						<option value="">Pilih Kategori</option>
						<option value="mobile">Mobile</option>
						<option value="website">Website</option>
						<option value="lainnya">Lainnya</option>
					</select>
				</div>
				<div class="col-md-2">
					<input type="text" placeholder="Tahun" name="tahun_lulus">
				</div>
				<div class="col-md-2">
					<button class="button" type="submit">Search</button>
				</div>
			</div>
		</form>
	</div>

	<div class="col-lg-12 col-md-12">
		<div class="dashboard-list-box margin-top-0">
			<h4>Daftar Aplikasi <a class="button pull-right" href="{{ url('admin/aplikasi/tambah') }}" style="background-color: #2ecc71">Tambah data</a></h4>

			@if (count($data) > 0)
			<ul>
				@foreach ($data as $key =>$isi)
				<li>
					<div class="list-box-listing">
						<div class="list-box-listing-img"><a href="#"><img src="{{ url('uploads/gambar_aplikasi/'.$isi->gambar_aplikasi) }}" alt=""></a></div>
						<div class="list-box-listing-content">
							<div class="inner">
								<h3>{{ $isi->nama_aplikasi }}</h3>
								<span>{{ $isi->nama_pembuat }}</span>
								<div class="star-rating" data-rating="5.0">
									<div class="rating-counter">(31 reviews)</div>
								</div>
							</div>
						</div>
					</div>
					<div class="buttons-to-right">
						<a href="#" class="button gray"><i class="sl sl-icon-note"></i> Edit</a>
						<a href="#" class="button gray"><i class="sl sl-icon-close"></i> Delete</a>
					</div>
				</li>
				@endforeach
				@else

				<div>
					<br><br>
					<center>Tidak Ada Hasil</center>
					<br><br>
				</div>
				@endif
			</ul>
		</div>
		{{ $data->render() }}
	</div>
</div>

@stop

resources/views/backend/dashboard.blade.php
@extends('backend.layout.index')
@section('content')
<!-- Dashboard -->

<!-- Content -->
<div class="dashboard-content">

	<!-- Titlebar -->
	<div id="titlebar">
		<div class="row">
			<div class="col-md-12">
				<h2>Howdy, Tom!</h2>
				<!-- Breadcrumbs -->
				<nav id="breadcrumbs">
					<ul>
						<li><a href="#">Home</a></li>
						<li>Dashboard</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>

	<!-- Notice -->
	<div class="row">
		<div class="col-md-12">
			<div class="notification success closeable margin-bottom-30">
				<p>Your listing <strong>Hotel Govendor</strong> has been approved!</p>
				<a class="close" href="#"></a>
			</div>
		</div>
	</div>

	<!-- Content -->
	<div class="row">

		<!-- Item -->
		<div class="col-lg-3 col-md-6">
			<div class="dashboard-stat color-1">
				<div class="dashboard-stat-content"><h4>6</h4> <span>Active Listings</span></div>
				<div class="dashboard-stat-icon"><i class="im im-icon-Map2"></i></div>
			</div>
		</div>

		<!-- Item -->
		<div class="col-lg-3 col-md-6">
			<div class="dashboard-stat color-2">
				<div class="dashboard-stat-content"><h4>726</h4> <span>Total Views</span></div>
				<div class="dashboard-stat-icon"><i class="im im-icon-Line-Chart"></i></div>
			</div>
		</div>


		<!-- Item -->
		<div class="col-lg-3 col-md-6">
			<div class="dashboard-stat color-3">
				<div class="dashboard-stat-content"><h4>95</h4> <span>Total Reviews</span></div>
				<div class="dashboard-stat-icon"><i class="im im-icon-Add-UserStar"></i></div>
			</div>
		</div>

		<!-- Item -->
		<div class="col-lg-3 col-md-6">
			<div class="dashboard-stat color-4">
				<div class="dashboard-stat-content"><h4>126</h4> <span>Times Bookmarked</span></div>
				<div class="dashboard-stat-icon"><i class="im im-icon-Heart"></i></div>
			</div>
		</div>
	</div>


	<div class="row">

		<!-- Recent Activity -->
		<div class="col-lg-6 col-md-12">
			<div class="dashboard-list-box with-icons margin-top-20">
				<h4>Recent Activities</h4>
				<ul>
					<li>
						<i class="list-box-icon sl sl-icon-layers"></i> Your listing <strong><a href="#">Hotel Govendor</a></strong> has been approved!
						<a href="#" class="close-list-item"><i class="fa fa-close"></i></a>
					</li>

					<li>
						<i class="list-box-icon sl sl-icon-star"></i> Kathy Brown left a review <div class="numerical-rating" data-rating="5.0"></div> on <strong><a href="#">Burger House</a></strong>
						<a href="#" class="close-list-item"><i class="fa fa-close"></i></a>
					</li>

					<li>
						<i class="list-box-icon sl sl-icon-heart"></i> Someone bookmarked your <strong><a href="#">Burger House</a></strong> listing!
						<a href="#" class="close-list-item"><i class="fa fa-close"></i></a>
					</li>

					<li>
						<i class="list-box-icon sl sl-icon-star"></i> Kathy Brown left a review <div class="numerical-rating" data-rating="3.0"></div> on <strong><a href="#">Airport</a></strong>
						<a href="#" class="close-list-item"><i class="fa fa-close"></i></a>
					</li>

					<li>
						<i class="list-box-icon sl sl-icon-heart"></i> Someone bookmarked your <strong><a href="#">Burger House</a></strong> listing!
						<a href="#" class="close-list-item"><i class="fa fa-close"></i></a>
					</li>

					<li>
						<i class="list-box-icon sl sl-icon-star"></i> John Doe left a review <div class="numerical-rating" data-rating="4.0"></div> on <strong><a href="#">Burger House</a></strong>
						<a href="#" class="close-list-item"><i class="fa fa-close"></i></a>
					</li>

					<li>
						<i class="list-box-icon sl sl-icon-star"></i> Jack Perry left a review <div class="numerical-rating" data-rating="2.5"></div> on <strong><a href="#">Tom's Restaurant</a></strong>
						<a href="#" class="close-list-item"><i class="fa fa-close"></i></a>
					</li>
				</ul>
			</div>
		</div>

		<!-- Invoices -->
		<div class="col-lg-6 col-md-12">
			<div class="dashboard-list-box invoices with-icons margin-top-20">
				<h4>Invoices</h4>
				<ul>

					<li><i class="list-box-icon sl sl-icon-doc"></i>
						<strong>Professional Plan</strong>
						<ul>
							<li class="unpaid">Unpaid</li>
							<li>Order: #00124</li>
							<li>Date: 20/07/2017</li>
						</ul>
						<div class="buttons-to-right">
							<a href="dashboard-invoice.html" class="button gray">View Invoice</a>
						</div>
					</li>

					<li><i class="list-box-icon sl sl-icon-doc"></i>
						<strong>Extended Plan</strong>
						<ul>
							<li class="paid">Paid</li>
							<li>Order: #00108</li>
							<li>Date: 14/07/2017</li>
						</ul>
						<div class="buttons-to-right">
							<a href="dashboard-invoice.html" class="button gray">View Invoice</a>
						</div>
					</li>

					<li><i class="list-box-icon sl sl-icon-doc"></i>
						<strong>Extended Plan</strong>
						<ul>
							<li class="paid">Paid</li>
							<li>Order: #00097</li>
							<li>Date: 10/07/2017</li>
						</ul>
						<div class="buttons-to-right">
							<a href="dashboard-invoice.html" class="button gray">View Invoice</a>
						</div>
					</li>

					<li><i class="list-box-icon sl sl-icon-doc"></i>
						<strong>Basic Plan</strong>
						<ul>
							<li class="paid">Paid</li>
							<li>Order: #00091</li>
							<li>Date: 30/06/2017</li>
						</ul>
						<div class="buttons-to-right">
							<a href="dashboard-invoice.html" class="button gray">View Invoice</a>
						</div>
					</li>

				</ul>
			</div>
		</div>
		@stop

resources/views/backend/kategori.blade.php
@extends('backend.layout.index')
@section('content')
<!-- Dashboard -->

<!-- Content -->
<div class="dashboard-content">

	<!-- Titlebar -->
	<div id="titlebar">
		<div class="row">
			<div class="col-md-12">
				<h2>Howdy, Tom!</h2>
				<!-- Breadcrumbs -->
				<nav id="breadcrumbs">
					<ul>
						<li><a href="#">Home</a></li>
						<li>Kategori</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>

	<!-- Notice -->
	<div class="row">
		<div class="col-md-12">
			<div class="notification success closeable margin-bottom-30">
				<p>Your listing <strong>Hotel Govendor</strong> has been approved!</p>
				<a class="close" href="#"></a>
			</div>
		</div>
	</div>

	<!-- Content -->

	<div class="row">
	</div>
</div>

@stop

resources/views/backend/layout/footer.blade.php
<!-- Copyrights -->
<div class="col-md-12">
	<div class="copyrights">© 2017 Listeo. All Rights Reserved.</div>
</div>
</div>

</div>
<!-- Content / End -->


</div>
<!-- Dashboard / End -->


</div>
<!-- Wrapper / End -->


<!-- Scripts -->
<script type="text/javascript" src="{!! asset('template/scripts/jquery-2.2.0.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/mmenu.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/chosen.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/slick.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/rangeslider.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/magnific-popup.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/waypoints.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/counterup.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/jquery-ui.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/tooltips.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/custom.js') !!}"></script>

<!-- Maps -->
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>
<script type="text/javascript" src="{!! asset('template/scripts/infobox.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/markerclusterer.js') !!}"></script>
<script type="text/javascript" src="{!! asset('template/scripts/maps.js') !!}"></script>

<!-- Booking Widget - Quantity Buttons -->
<script src="{!! asset('template/scripts/quantityButtons.js') !!}"></script>

<!-- Date Range Picker - docs: http://www.daterangepicker.com/ -->
<script src="{!! asset('template/scripts/moment.min.js') !!}"></script>
<script src="{!! asset('template/scripts/daterangepicker.js') !!}"></script>

resources/views/backend/layout/header.blade.php
<!-- Wrapper -->
<div id="wrapper">

<!-- Header Container
	================================================== -->
	<header id="header-container" class="fixed fullwidth dashboard">

		<!-- Header -->
		<div id="header" class="not-sticky">
			<div class="container">

				<!-- Left Side Content -->
				<div class="left-side">

					<!-- Logo -->
					<div id="logo">
						<a href="index.html"><img src="images/logo.png" alt=""></a>
						<a href="{{ url('/') }}" class="dashboard-logo"><img src="{!! asset('template/images/logo2.png') !!}" alt=""></a>
					</div>

				</div>
				<!-- Left Side Content / End -->

				<!-- Right Side Content / End -->
				<div class="right-side">
					<!-- Header Widget -->
					<div class="header-widget">

						<!-- User Menu -->
						<div class="user-menu">
							<div class="user-name"><span><img src="images/dashboard-avatar.jpg" alt=""></span>My Account</div>
							<ul>
								<li><a href="dashboard.html"><i class="sl sl-icon-settings"></i> Dashboard</a></li>
								<li><a href="dashboard-messages.html"><i class="sl sl-icon-user"></i> Profil Saya</a></li>
								<li><a href="index.html"><i class="sl sl-icon-power"></i> Logout</a></li>
							</ul>
						</div>


					</div>
					<!-- Header Widget / End -->
				</div>
				<!-- Right Side Content / End -->

			</div>
		</div>
		<!-- Header / End -->

	</header>
	<div class="clearfix"></div>
<!-- Header Container / End -->

resources/views/backend/layout/index.blade.php
<!DOCTYPE html>
<head>

	<!-- Basic Page Needs-->
	<title>Tugas Akhir</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS -->
	<link rel="stylesheet" href="{!! asset('template/css/style.css') !!}">
	<link rel="stylesheet" href="{!! asset('template/css/colors/main.css') !!}" id="colors">

</head>

<body>

	@include('backend.layout.header')

	@include('backend.layout.navbar')

	@yield('content')

	@include('backend.layout.footer')

</body>
</html>

resources/views/backend/layout/navbar.blade.php
<div id="dashboard">

	<!-- Navigation-->

	<!-- Responsive Navigation Trigger -->
	<a href="#" class="dashboard-responsive-nav-trigger"><i class="fa fa-reorder"></i> Dashboard Navigation</a>

	<div class="dashboard-nav">
		<div class="dashboard-nav-inner">

			<ul data-submenu-title="Main">
				<li class="{{ Request::is('admin') ? 'active' : '' }}">
					<a href="{{ url('admin/')}}"><i class="sl sl-icon-settings"></i> Dashboard</a>
				</li>
			</ul>

			<ul data-submenu-title="Listings">
				<li class="{{ Request::is('admin/aplikasi' || 'admin/kategori') ? 'active' : '' }}">
					<a><i class="sl sl-icon-layers"></i> Data</a>
					<ul>
						<li class="{{ Request::is('admin/aplikasi' || 'admin/aplikasi/tambah') ? 'active' : '' }}" >
							<a href="{{ url('admin/aplikasi') }}"> Aplikasi</a>
						</li>
						<li class="{{ Request::is('admin/kategori') ? 'active' : '' }}" >
							<a href="{{ url('admin/kategori') }}"> Kategori</a>
						</li>
					</ul>	
				</li>
			</ul>	

			<ul data-submenu-title="Account">
				<li><a href="dashboard-my-profile.html"><i class="sl sl-icon-user"></i> Profil Saya</a></li>
				<li><a href="index.html"><i class="sl sl-icon-power"></i> Logout</a></li>
			</ul>

		</div>
	</div>
	<!-- Navigation / End -->

resources/views/backend/tambah_aplikasi.blade.php
@extends('backend.layout.index')
@section('content')
<!-- Dashboard -->

<!-- Content -->
<div class="dashboard-content">

	<!-- Titlebar -->
	<div id="titlebar">
		<div class="row">
			<div class="col-md-12">
				<h2>Howdy, Tom!</h2>
				<!-- Breadcrumbs -->
				<nav id="breadcrumbs">
					<ul>
						<li><a href="#">Home</a></li>
						<li>Tambah Aplikasi</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>

	<!-- Notice -->
	<!-- <div class="row">
		<div class="col-md-12">
			<div class="notification success closeable margin-bottom-30">
				<p>Your listing <strong>Hotel Govendor</strong> has been approved!</p>
				<a class="close" href="#"></a>
			</div>
		</div>
	</div> -->

	<!-- Content -->

	<div class="col-lg-12 col-md-12">
		<div class="dashboard-list-box margin-top-0">
			<h4 class="gray">Tambah Aplikasi</h4>
			<div class="dashboard-list-box-static">

				<form action="{{ route('BackendController.store') }}" method="post" enctype="multipart/form-data">
					{!! csrf_field() !!}
					<!-- Avatar -->
					<div class="edit-profile-photo">
						<img src="{!! asset('template/images/user-avatar.jpg') !!}" alt="">
						<div class="change-photo-btn">
							<div class="photoUpload">
								<span><i class="fa fa-upload"></i> Unggah foto</span>
								<input type="file" class="upload" name="gambar_aplikasi">
							</div>
						</div>
					</div>

					<!-- Details -->
					<div class="my-profile">

						<label>Nama Aplikasi</label>
						<input type="text" placeholder="Masukan Nama Aplikasi" name="nama_aplikasi">

						<label>Kategori Aplikasi</label>
						<select name="kategori_aplikasi">
							<option value="mobile">Mobile</option>
							<option value="website">Website</option>
							<option value="lainnya">Lainnya</option>
						</select>

						<label>NIM</label>
						<input type="text" placeholder="Masukan NIM" name="nim">

						<label>Nama Pembuat</label>
						<input type="text" placeholder="Masukan Nama Pembuat" name="nama_pembuat">

						<label>Tahun Lulus</label>
						<input type="text" placeholder="Masukan Tahun Lulus" name="tahun_lulus">

						<label>Deskripsi Aplikasi</label>
						<textarea id="notes" cols="30" rows="10" name="deskripsi_aplikasi">Tuliskan Deskripsi Aplikasi Disini..</textarea>

						<label><i class="fa fa-globe"></i> Alamat Tautan</label>
						<input style="margin-bottom: 0px" placeholder="https://www.google.com/" type="text" name="alamat_tautan">
						<small >*Sertakan "http://" pada awal penulisan tautan</small>
					</div>
					<input type="submit" class=" pull-right button margin-top-15" value="Simpan">
					<div class="clearfix"></div>
				</form>

			</div>
		</div>
	</div>
</div>

@stop